package com.indra.elections.peruvian.services;

/**
 * Created by lm2a on 08/06/2017.
 */

public class TestFile {
    public static final String JSON_1 = "{\"Colegio\":\"1001999099900\",\"Eleccion\":{\"Censo\":484,\"ElectionName\":\"PRESIDENTE Y VICEPRESIDENTES\",\"Partidos\":[{\"Value\":1,\"idPartido\":\"1\",\"siglas\":\"AN\"},{\"Value\":0,\"idPartido\":\"2\",\"siglas\":\"PA\"},{\"Value\":0,\"idPartido\":\"3\",\"siglas\":\"GL\"},{\"Value\":0,\"idPartido\":\"4\",\"siglas\":\"LL\"},{\"Value\":1,\"idPartido\":\"5\",\"siglas\":\"CD\"},{\"Value\":0,\"idPartido\":\"6\",\"siglas\":\"OLL\"},{\"Value\":0,\"idPartido\":\"7\",\"siglas\":\"TM\"},{\"Value\":0,\"idPartido\":\"9\",\"siglas\":\"SA\"},{\"Value\":0,\"idPartido\":\"10\",\"siglas\":\"JA\"},{\"Value\":0,\"idPartido\":\"11\",\"siglas\":\"AI\"},{\"Value\":0,\"idPartido\":\"12\",\"siglas\":\"MA\"},{\"Value\":0,\"idPartido\":\"13\",\"siglas\":\"PP\"},{\"Value\":0,\"idPartido\":\"14\",\"siglas\":\"TA\"},{\"Value\":0,\"idPartido\":\"15\",\"siglas\":\"MV\"}],\"Registrados\":250,\"VotosAdjudicadosManualmente\":3,\"VotosBlancos\":1,\"VotosEmitidos\":5,\"VotosNulos\":2,\"VotosValidos\":2},\"Fecha\":\"2017-06-01 13:06:46\",\"Maquina\":\"101F74EB9AE2\",\"Municipio\":\"MUNICIPIO DEMO\",\"Provincia\":\"PROVINCIA LA GALAXIA\",\"TipoMaquina\":\"UE\",\"Version\":\"V1.0\"}";
    public static final String JSON_2 = "{\"Colegio\":\"1001999099900\",\"Eleccion\":{\"Censo\":484,\"ElectionName\":\"PRESIDENTE REGIONAL Y VICEPRESIDENTE\",\"Partidos\":[{\"Value\":0,\"idPartido\":\"1\",\"siglas\":\"AN\"},{\"Value\":0,\"idPartido\":\"2\",\"siglas\":\"PA\"},{\"Value\":1,\"idPartido\":\"3\",\"siglas\":\"GL\"},{\"Value\":0,\"idPartido\":\"4\",\"siglas\":\"LL\"},{\"Value\":0,\"idPartido\":\"6\",\"siglas\":\"OLL\"},{\"Value\":0,\"idPartido\":\"7\",\"siglas\":\"TM\"},{\"Value\":0,\"idPartido\":\"8\",\"siglas\":\"HV\"},{\"Value\":0,\"idPartido\":\"9\",\"siglas\":\"SA\"},{\"Value\":0,\"idPartido\":\"11\",\"siglas\":\"AI\"},{\"Value\":0,\"idPartido\":\"12\",\"siglas\":\"MA\"},{\"Value\":1,\"idPartido\":\"13\",\"siglas\":\"PP\"},{\"Value\":0,\"idPartido\":\"14\",\"siglas\":\"TA\"},{\"Value\":0,\"idPartido\":\"15\",\"siglas\":\"MV\"}],\"Registrados\":250,\"VotosAdjudicadosManualmente\":3,\"VotosBlancos\":1,\"VotosEmitidos\":5,\"VotosNulos\":2,\"VotosValidos\":2},\"Fecha\":\"2017-06-01 13:06:46\",\"Maquina\":\"101F74EB9AE2\",\"Municipio\":\"MUNICIPIO DEMO\",\"Provincia\":\"PROVINCIA LA GALAXIA\",\"TipoMaquina\":\"UE\",\"Version\":\"V1.0\"}";
    public static final String JSON_3 = "{\"Colegio\":\"1001999099900\",\"Eleccion\":{\"Censo\":484,\"ElectionName\":\"CONSEJERO REGIONAL\",\"Partidos\":[{\"Value\":0,\"idPartido\":\"1\",\"siglas\":\"AN\"},{\"Value\":1,\"idPartido\":\"2\",\"siglas\":\"PA\"},{\"Value\":0,\"idPartido\":\"3\",\"siglas\":\"GL\"},{\"Value\":1,\"idPartido\":\"4\",\"siglas\":\"LL\"},{\"Value\":0,\"idPartido\":\"5\",\"siglas\":\"CD\"},{\"Value\":0,\"idPartido\":\"6\",\"siglas\":\"OLL\"},{\"Value\":0,\"idPartido\":\"7\",\"siglas\":\"TM\"},{\"Value\":0,\"idPartido\":\"8\",\"siglas\":\"HV\"},{\"Value\":0,\"idPartido\":\"9\",\"siglas\":\"SA\"},{\"Value\":0,\"idPartido\":\"10\",\"siglas\":\"JA\"},{\"Value\":0,\"idPartido\":\"11\",\"siglas\":\"AI\"},{\"Value\":0,\"idPartido\":\"12\",\"siglas\":\"MA\"},{\"Value\":0,\"idPartido\":\"13\",\"siglas\":\"PP\"},{\"Value\":0,\"idPartido\":\"14\",\"siglas\":\"TA\"}],\"Registrados\":250,\"VotosAdjudicadosManualmente\":3,\"VotosBlancos\":1,\"VotosEmitidos\":5,\"VotosNulos\":2,\"VotosValidos\":2},\"Fecha\":\"2017-06-01 13:06:46\",\"Maquina\":\"101F74EB9AE2\",\"Municipio\":\"MUNICIPIO DEMO\",\"Provincia\":\"PROVINCIA LA GALAXIA\",\"TipoMaquina\":\"UE\",\"Version\":\"V1.0\"}";
}
